version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nginx
    ports:
      - "80:80"
    container_name: proxy-nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"